"""Verify that encoder.py produces byte-for-byte identical output to golden files.

Run after extracting the encoder to ensure nothing changed.
Usage:  python3 tests/verify_goldens.py

Requires tests/goldens/ generated by generate_goldens.py.
"""
import io, os, sys, struct, json
from binascii import hexlify

REPO_ROOT = os.path.dirname(os.path.dirname(__file__))
sys.path.insert(0, REPO_ROOT)
import encoder

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "goldens")

TEST_GUID      = "abc12345-1234-5678-9012-abcdef000001"
TEST_GUID2     = "def67890-1234-5678-9012-abcdef000002"
TEST_NAME      = "TestName"
TEST_DECK_NAME = "TestDeck"
TEST_ITEM_ID   = 1001
TEST_CARD_ID   = 5000

failed = 0
passed = 0


def check(name, got):
    global passed, failed
    path = os.path.join(GOLDEN_DIR, f"{name}.golden")
    if not os.path.exists(path):
        print(f"  SKIP {name}: golden file not found")
        return
    with open(path, "rb") as f:
        expected = f.read()
    if got == expected:
        passed += 1
        print(f"  PASS {name} ({len(got)} bytes)")
    else:
        failed += 1
        print(f"  FAIL {name}: expected {len(expected)} bytes, got {len(got)}")
        # Show first difference
        for i, (e, g) in enumerate(zip(expected, got)):
            if e != g:
                ctx = max(0, i - 20)
                print(f"    first diff at byte {i}: expected {e:02x}, got {g:02x}")
                print(f"    expected[{ctx}:{i+20}]: {expected[ctx:i+20]!r}")
                print(f"    got[{ctx}:{i+20}]:      {got[ctx:i+20]!r}")
                break
        else:
            if len(expected) != len(got):
                shorter = min(len(expected), len(got))
                print(f"    all {shorter} bytes match, but lengths differ")


# ── encode_objfmt_response variants ─────────────────────────────────

def verify_objfmt_response_basic():
    type_names = ["Test.Basic"]
    fields = [
        ("MyInt",    "int",    42),
        ("MyUlong",  "ulong",  1234),
        ("MyBool",   "bool",   True),
        ("MyBoolF",  "bool",   False),
        ("MyGuid",   "guid",   "12345678-1234-5678-9012-123456789012"),
        ("MyStr",    "string", "hello"),
    ]
    check("encode_objfmt_response_basic",
          encoder.encode_objfmt_response(type_names, fields))


def verify_objfmt_response_enum1():
    type_names = ["Test.WithEnum", "Test.MyEnum", "System.Int32"]
    fields = [("Error", "enum1", ("Test.MyEnum", 0))]
    check("encode_objfmt_response_enum1",
          encoder.encode_objfmt_response(type_names, fields))


def verify_objfmt_response_uid():
    type_names = ["Test.WithUid", "Game.Shared.UID", "System.UInt64"]
    fields = [("PlayerId", "uid", 67890)]
    check("encode_objfmt_response_uid",
          encoder.encode_objfmt_response(type_names, fields))


def verify_objfmt_response_struct():
    type_names = ["Test.WithStruct", "Test.SubType", "System.Int32", "System.String"]
    fields = [("Inner", "struct", ("Test.SubType", [("X", "int", 1), ("Y", "string", "hi")]))]
    check("encode_objfmt_response_struct",
          encoder.encode_objfmt_response(type_names, fields))


def verify_objfmt_response_raw():
    type_names = ["Test.WithRaw", "System.Byte[]"]
    fields = [("Data", "raw", ("System.Byte[]", b"\x01\x02\x03"))]
    check("encode_objfmt_response_raw",
          encoder.encode_objfmt_response(type_names, fields))


def verify_objfmt_response_coll():
    type_names = ["Test.WithColl",
                  "System.Collections.Generic.List`1#Game.Shared.Domain.inventory_bits",
                  "Game.Shared.Domain.inventory_bits",
                  "System.UInt64", "Game.Shared.ResourceId", "System.Guid",
                  "System.Boolean", "System.Int32", "System.DateTime", "System.String"]
    fields = [("Items", "coll", (type_names[1], 2,
        [(TEST_GUID, 1001, 3), (TEST_GUID2, 1002, 1)]))]
    check("encode_objfmt_response_coll",
          encoder.encode_objfmt_response(type_names, fields))


def verify_objfmt_response_cardlist():
    type_names = ["Test.WithCards",
                  "System.Collections.Generic.List`1#Game.Shared.Domain.card_instance_bits",
                  "Game.Shared.Domain.card_instance_bits",
                  "System.UInt64", "Game.Shared.ResourceId", "System.Guid",
                  "System.Boolean", "System.String"]
    fields = [("Cards", "cardlist", (type_names[1], 1,
        [(TEST_GUID, "Bunoshi", TEST_CARD_ID, 3, 2, 2)]))]
    check("encode_objfmt_response_cardlist",
          encoder.encode_objfmt_response(type_names, fields))


def verify_objfmt_response_class():
    type_names = ["Test.WithClass"]
    fields = [("NullField", "class", "Test.SomeClass")]
    check("encode_objfmt_response_class",
          encoder.encode_objfmt_response(type_names, fields))


def verify_objfmt_response_zeroprop():
    type_names = ["Test.ZeroPropsHeader", "System.Int32", "System.String"]
    buf = io.BytesIO()
    sizes = [0]
    def w(s): buf.write(s.encode("utf-8"))
    def s():  buf.write(b";")
    w(""); s(); w("00"); s(); w("0"); s(); w("2"); s()
    f1 = buf.tell(); sizes.append(0)
    w("A"); s(); w("1"); s(); w(str(type_names.index("System.Int32"))); s(); w("0"); s()
    w(hexlify(struct.pack("<i", 99)).decode("ascii")); s()
    sizes[-1] = buf.tell() - f1
    f2 = buf.tell(); sizes.append(0)
    w("B"); s(); w("2"); s(); w(str(type_names.index("System.String"))); s(); w("0"); s()
    enc = b"test"; w(str(len(enc))); s(); buf.write(enc)
    sizes[-1] = buf.tell() - f2
    sizes[0] = buf.tell()
    w(";".join(type_names)); buf.write(b"\n")
    for i, z in enumerate(sizes):
        if i > 0: w(";")
        w(str(z))
    check("encode_objfmt_response_zeroprop", buf.getvalue())


# ── element encoders ─────────────────────────────────────────────────

def verify_encode_inventory_item():
    sizes = []
    buf = io.BytesIO()
    w = lambda s: buf.write(s.encode("utf-8"))
    s = lambda: buf.write(b";")
    sizes.append(0)
    w(""); s(); w("0"); s(); w("0"); s(); w("1"); s()

    f = buf.tell(); sizes.append(0)
    w("Items"); s(); w("1"); s()
    type_names = ["Test.Items",
                  "System.Collections.Generic.List`1#Game.Shared.Domain.inventory_bits",
                  "Game.Shared.Domain.inventory_bits",
                  "System.UInt64", "Game.Shared.ResourceId", "System.Guid",
                  "System.Boolean", "System.Int32", "System.DateTime", "System.String"]
    def ft(tn):
        if tn not in type_names: type_names.append(tn)
        return type_names.index(tn)
    w(str(ft(type_names[1]))); s(); w("0"); s(); w("1"); s()
    encoder.encode_inventory_item(buf, sizes, ft, TEST_GUID, TEST_ITEM_ID, 0, 3, bound=True)
    sizes[1] = buf.tell() - f; sizes[0] = buf.tell()
    w(";".join(type_names)); buf.write(b"\n")
    for i, sz in enumerate(sizes):
        if i > 0: w(";")
        w(str(sz))
    check("encode_inventory_item", buf.getvalue())


def verify_encode_card_instance():
    sizes = []
    buf = io.BytesIO()
    w = lambda s: buf.write(s.encode("utf-8"))
    s = lambda: buf.write(b";")
    sizes.append(0)
    w(""); s(); w("0"); s(); w("0"); s(); w("1"); s()

    f = buf.tell(); sizes.append(0)
    w("Cards"); s(); w("1"); s()
    type_names = ["Test.Cards",
                  "System.Collections.Generic.List`1#Game.Shared.Domain.card_instance_bits",
                  "Game.Shared.Domain.card_instance_bits",
                  "System.UInt64", "Game.Shared.ResourceId", "System.Guid",
                  "System.Boolean", "System.String"]
    def ft(tn):
        if tn not in type_names: type_names.append(tn)
        return type_names.index(tn)
    w(str(ft(type_names[1]))); s(); w("0"); s(); w("1"); s()
    encoder.encode_card_instance(buf, sizes, ft, TEST_GUID, TEST_NAME, TEST_CARD_ID, 3, 2, 2, 0)
    sizes[1] = buf.tell() - f; sizes[0] = buf.tell()
    w(";".join(type_names)); buf.write(b"\n")
    for i, sz in enumerate(sizes):
        if i > 0: w(";")
        w(str(sz))
    check("encode_card_instance", buf.getvalue())


def verify_encode_deck_bits():
    sizes = []
    buf = io.BytesIO()
    w = lambda s: buf.write(s.encode("utf-8"))
    s = lambda: buf.write(b";")
    sizes.append(0)
    w(""); s(); w("0"); s(); w("0"); s(); w("1"); s()

    f = buf.tell(); sizes.append(0)
    w("Decks"); s(); w("1"); s()
    type_names = ["Test.Decks",
                  "System.Collections.Generic.List`1#Game.Shared.Domain.deck_bits",
                  "Game.Shared.Domain.deck_bits",
                  "System.UInt64", "System.String",
                  "Game.Shared.ResourceId", "System.Guid",
                  "System.Collections.Generic.List`1#Game.Shared.Domain.card_instance_bits",
                  "System.Collections.Generic.Dictionary`2#System.UInt64!Game.Shared.Mechanics.EGemTypesNew",
                  "Game.Shared.Mechanics.EDeckLock", "System.Int32",
                  "Game.Shared.Mechanics.EDeckPersonality",
                  "System.Boolean"]
    def ft(tn):
        if tn not in type_names: type_names.append(tn)
        return type_names.index(tn)
    w(str(ft(type_names[1]))); s(); w("0"); s(); w("1"); s()
    encoder.encode_deck_bits(buf, sizes, ft, TEST_DECK_NAME, TEST_DECK_NAME, 1, 0, [], 0)
    sizes[1] = buf.tell() - f; sizes[0] = buf.tell()
    w(";".join(type_names)); buf.write(b"\n")
    for i, sz in enumerate(sizes):
        if i > 0: w(";")
        w(str(sz))
    check("encode_deck_bits", buf.getvalue())


def verify_encode_champion_bits_minimal():
    sizes = []
    buf = io.BytesIO()
    w = lambda s: buf.write(s.encode("utf-8"))
    s = lambda: buf.write(b";")
    sizes.append(0)
    w(""); s(); w("0"); s(); w("0"); s(); w("1"); s()

    f = buf.tell(); sizes.append(0)
    w("Champions"); s(); w("1"); s()
    type_names = ["Test.Champs",
                  "System.Collections.Generic.List`1#Game.Shared.Domain.champion_bits",
                  "Game.Shared.Domain.champion_bits",
                  "System.String", "System.UInt64", "System.Int32",
                  "Game.Shared.Mechanics.EChampionClass",
                  "Game.Shared.Mechanics.ERace",
                  "Game.Shared.Mechanics.EGender"]
    def ft(tn):
        if tn not in type_names: type_names.append(tn)
        return type_names.index(tn)
    w(str(ft(type_names[1]))); s(); w("0"); s(); w("1"); s()
    encoder.encode_champion_bits_minimal(buf, sizes, ft,
                                         12345, "TestChamp", 5000,
                                         1, 0, 3, 1, 1, 0)
    sizes[1] = buf.tell() - f; sizes[0] = buf.tell()
    w(";".join(type_names)); buf.write(b"\n")
    for i, sz in enumerate(sizes):
        if i > 0: w(";")
        w(str(sz))
    check("encode_champion_bits_minimal", buf.getvalue())


# ── high-level encoders ──────────────────────────────────────────────

def verify_objfmt_string():
    check("encode_objfmt_string_hello", encoder.encode_objfmt_string("hello"))
    check("encode_objfmt_string_empty", encoder.encode_objfmt_string(""))


def verify_session_state():
    check("encode_session_state", encoder.encode_session_state(42, "TestSession"))


def verify_campaign_session_state():
    check("encode_campaign_session_state",
          encoder.encode_campaign_session_state(
              42, "camp_1",
              "abc12345-1234-5678-9012-abcdef000001",
              session_flags=1 | 4))


def verify_sync_event():
    import game_engine
    pkt = game_engine.NetworkPacketSessionEventArgs()
    pkt.player_id   = game_engine.UID(67890)
    pkt.session_id  = game_engine.UID(12345)
    pkt.event_ids   = [1, 2, 3]
    pkt.event_data  = [b"test_event_data_12345678"]
    check("encode_sync_event", encoder.encode_sync_event(pkt))


def verify_challenger_list():
    challengers = [
        {"id": 1, "name": "BossOne", "deck": TEST_GUID, "boss": "True"},
        {"id": 2, "name": "MinionTwo", "deck": TEST_GUID2, "boss": "False"},
    ]
    check("encode_challenger_list", encoder.encode_challenger_list(challengers))


def verify_get_challengers_response():
    challengers = [{"id": 1, "name": "BossOne", "deck": TEST_GUID, "boss": "True"}]
    check("encode_get_challengers_response",
          encoder.encode_get_challengers_response(True, challengers))


def verify_login_stream_done():
    check("encode_login_stream_done", encoder.encode_login_stream_done())


def verify_datawrapper():
    global passed
    body = b"test body payload 42"
    check("encode_datawrapper",
          encoder.encode_datawrapper(1, 2127, body, 0))
    # The compressed version depends on gzip output, which may vary between Python versions.
    # Skip byte-for-byte comparison — verify it's valid instead.
    dw = encoder.encode_datawrapper(1, 2127, body, 1)
    assert b"DataWrapper" in dw, "compressed datawrapper missing type name"
    passed += 1
    print(f"  PASS encode_datawrapper_compressed ({len(dw)} bytes, compression verified)")


def verify_mail_count():
    check("encode_get_unread_mail_count_response",
          encoder.encode_get_unread_mail_count_response(0))
    check("encode_get_unread_mail_count_response_5",
          encoder.encode_get_unread_mail_count_response(5))


def verify_ping_mail():
    check("encode_ping_mail_server_response",
          encoder.encode_ping_mail_server_response("01/15/2025 12:00:00"))


def verify_profile_response():
    env = json.dumps({"test": True}).encode("utf-8")
    check("encode_profile_response", encoder.encode_profile_response(env))


def verify_store_response():
    items = [
        {"n": "Test Booster", "s": "A test booster pack", "price": 200,
         "currency": "Gold", "template_guid": TEST_GUID, "t": "ShopBoosterTab"},
        {"n": "Starter Deck", "s": "Beginner deck", "price": 1000,
         "currency": "Platinum", "template_guid": TEST_GUID2, "t": "collectordeck"},
    ]
    check("encode_store_response", encoder.encode_store_response(items))
    check("encode_store_response_empty", encoder.encode_store_response([]))


def verify_session_event_streams():
    """Verify the phase/combat/ability SessionEventArgs streams the server
    pushes to the client (class-255 NetworkPacket bytes) against tests/goldens."""
    import game_engine as ge

    pl = ge.UID.make(244, 1001)
    ai = ge.UID.make(3, 1000)
    troop = ge.SessionCardId(ge.UID.make(1, 5001))
    ai_champ = ge.SessionCardId(ge.UID.make(1, 5000))

    def snapshot(name, game):
        pkt = game.make_network_packet(pl)
        check(name, encoder.encode_sync_event(pkt))

    # DeclareCombatPriorityWindow stop.
    g = ge.Game(42, pl, ai)
    g.player_resources = 3
    g.player_total_resources = 4
    g.player_charges = 2
    g.player_spell_points = 1
    g.ai_health = 10
    g.push_turn_phase(ge.ETurnPhases.DeclareCombatPriorityWindow, pl, pl)
    g.push_green_light(pl, ge.EPriorityContext.ProcedeToCombat)
    g.push_player_updated(pl, champ_id=ge.SessionCardId(ge.UID.make(1, 6000)))
    g.push_player_updated(ai, champ_id=ai_champ)
    snapshot("sync_combat_window", g)

    # DeclareAttack: attacker committed.
    g = ge.Game(42, pl, ai)
    g.player_resources = 3
    g.player_total_resources = 4
    g.push_attack_declared(ge.CombatId(pl, 1), pl, ai_champ, troop)
    cs = ge.CombatSessionEventArgs()
    cs.player_id = pl
    cs.id = ge.CombatId(pl, 1)
    cs.attacker = troop
    cs.blockers = []
    g.push_combat_listing(pl, [cs])
    snapshot("sync_declare_attack", g)

    # AssignDamage combat damage.
    g = ge.Game(42, pl, ai)
    g.ai_health = 8
    g.push_combat_phase_resolved(ge.CombatId(pl, 1), troop, ai_champ, [])
    ev = ge.ChampionHealthChangedSessionEventArgs()
    ev.player_id = ai
    ev.old_damage_value = 10
    ev.new_damage_value = 8
    g._push(ev)
    g.push_player_updated(ai, champ_id=ai_champ)
    snapshot("sync_combat_damage", g)

    # CardUpdated with a manual troop ability (Shift).
    g = ge.Game(42, pl, ai)
    cdef = ge.CardDef("Gemsoul Feeder", ge.ECardTypes.Troop, 2, 1, 2, [],
                     [ge.ResourceId.from_str("44605164-fbfc-d2f7-433a-ebf79d35adff"),
                      ge.ResourceId.from_str("2af60616-96ee-743d-33b8-cdb4c3d9f0a5")],
                     ge.ECardAttributes.SpiritDrain)
    g.card_defs[troop] = cdef
    g.push_card_updated(troop, pl, ge.ECardCollections.Warzone, ge.ECardTypes.Troop,
                        template_id="7071ddd7-b81b-46b2-8682-9f391ab3f12e",
                        attributes=ge.ECardAttributes.SpiritDrain)
    snapshot("sync_troop_ability_card", g)

    # ShiftPower transfer (source loses Lifedrain, target gains).
    g = ge.Game(42, pl, ai)
    src = ge.SessionCardId(ge.UID.make(1, 7001))
    tgt = ge.SessionCardId(ge.UID.make(1, 7002))
    for scid, nm, ab, attrs in (
        (src, "Gemsoul Feeder", ["44605164-fbfc-d2f7-433a-ebf79d35adff", "2af60616-96ee-743d-33b8-cdb4c3d9f0a5"], ge.ECardAttributes.SpiritDrain),
        (tgt, "Shin'hare Militia", [], 0),
    ):
        cdef = ge.CardDef(nm, ge.ECardTypes.Troop, 2, 1, 2, [],
                          [ge.ResourceId.from_str(a) for a in ab], attrs)
        g.card_defs[scid] = cdef
        g.push_card_updated(scid, pl, ge.ECardCollections.Warzone, ge.ECardTypes.Troop,
                            template_id="7071ddd7-b81b-46b2-8682-9f391ab3f12e",
                            attributes=attrs)
    snapshot("sync_shift_transfer", g)


TESTS = [
    verify_objfmt_response_basic,
    verify_objfmt_response_enum1,
    verify_objfmt_response_uid,
    verify_objfmt_response_struct,
    verify_objfmt_response_raw,
    verify_objfmt_response_coll,
    verify_objfmt_response_cardlist,
    verify_objfmt_response_class,
    verify_objfmt_response_zeroprop,
    verify_encode_inventory_item,
    verify_encode_card_instance,
    verify_encode_deck_bits,
    verify_encode_champion_bits_minimal,
    verify_objfmt_string,
    verify_session_state,
    verify_campaign_session_state,
    verify_sync_event,
    verify_challenger_list,
    verify_get_challengers_response,
    verify_login_stream_done,
    verify_datawrapper,
    verify_mail_count,
    verify_ping_mail,
    verify_profile_response,
    verify_store_response,
    verify_session_event_streams,
]


def main():
    global passed, failed
    for fn in TESTS:
        try:
            fn()
        except Exception as e:
            failed += 1
            print(f"  FAIL {fn.__name__}: {e}")
            import traceback
            traceback.print_exc()

    print(f"\n{passed} passed, {failed} failed")
    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
