"""Python implementation of the ``HexClient/Game.Shared`` rules boundary.

RulesPort owns gameplay decisions, state transitions, ordering, and
continuations.  Runtime adapters project accepted transitions into SQLite and
HConnect events; the legacy resolver is retained only for explicitly disabled
rollback sessions and is never selected by an attached live session.
"""

from .kernel import (
    AbilityRegistry,
    Chain,
    GameAction,
    GameActionResult,
    GameActionStack,
    MultiplyWithCarryRng,
    PriorityWindowAction,
    TurnPhasePlayers,
)
from .phases import (permitted_next_phases, require_legal_transition,
                     transition_is_legal)
from .session import (AuthoritativeSession, GameEngineEventSink,
                      RulesTransaction, SQLiteRulesSnapshot)
from .pvp_session import PvpAuthoritativeSession
from .transactions import (AbilityCanBeActivatedRequirement,
                           AbilityExistsRequirement,
                           AbilityHasValidTargetsRequirement, AndRequirement,
                           AbilityHasTriggerRequirement,
                           AbilityCostRequirement,
                           AbilityIsManuallyActivatedRequirement,
                           AbilitiesAreTriggeredRequirement,
                           AllDamageAssignedRequirement, AttackExistsRequirement,
                           BlocksAreValidRequirement,
                           AttackerIsValidRequirement,
                           CardCanBePlayedRequirement,
                           CardCanUntapRequirement,
                           CardUntappedRequirement,
                           CardCastingCostRequirement,
                           CardInCollectionRequirement,
                           CardResourceThresholdRequirement,
                           CardTappedRequirement, CardTypeRequirement,
                           CardInPlayableLocationRequirement,
                           CardCountRequirement,
                           SpaceInCardCollectionRequirement,
                           PlayerHasChargePointsRequirement,
                           PlayerIsInactiveRequirement,
                           PlayerIsStartingPlayerRequirement,
                           PlayerHasResourceCountRequirement,
                           SessionCardAttributesRequirement,
                           SpellAllowedInTurnPhaseRequirement,
                           TurnCountRequirement,
                           DefenseDeclarationsLegalRequirement,
                           EmptyChainRequirement, MainPhaseRequirement,
                           NotRequirement, OrRequirement,
                           PlayerHasPriorityRequirement,
                           PlayerIsActiveRequirement,
                           PlayerIsAtFrontOfTriggeredAbilityQueueRequirement,
                           PlayerIsNotEliminatedRequirement,
                           PlayerIsResponsibleForAbilityRequirement,
                           PriorityWindowRequirement, TurnPhaseRequirement,
                           XCostRequirement)
from .transactions import requirement_from_metadata
from .transactions import EComparisons
from .coverage import (TRANSACTION_COVERAGE, FILTER_COVERAGE, coverage_summary,
                       coverage_report, validate_transaction_coverage,
                       validate_filter_coverage, validate_effect_coverage,
                       STRUCTURAL_EFFECTS, STAGED_EFFECTS)
from .abilities import AbilityFactory, AbilityInstance
from .adapter import (rules_session_for, session_from_persisted_game,
                      pvp_session_from_persisted_game, enable_rules_port)
from .projections import TransactionProjection
from .runtime_adapter import (PvpRuntimeFacts, RuntimeCard, RuntimePlayer,
                              SQLiteCardMutationAdapter, attach_pvp_runtime_facts)
from .combat import (Combat, CombatFlags, CombatId, CombatManager, CombatPhase,
                     CombatResolver, CombatResult, CombatDamageBackend)
from .combat_rules import player_has_eligible_attackers
from .turn_states import (ConditionalPhaseState, FirstMainPhaseState,
                          PriorityPhaseState, StartTurnState, TurnPhaseState,
                          TurnPhaseTrigger)
from .parity import (ParityCapture, ParityMismatch, compare_captures,
                     event_record, replay_transactions)
from .actions import (AbilityResolutionState, PushOntoChainAction,
                      ResolveTopOfChainAction)
from .costs import (AbilityCostPlan, AbilityCostTarget, plan_ability_cost,
                    apply_ability_cost_plan, ability_cost_targets,
                    cost_type_for_kind, card_cost_targets)
from .resources import (ResourceChange, ResourcePlay, apply_resource_change,
                        play_resource, play_resource_for_player,
                        pay_resource_for_player, pay_charge_for_player,
                        pay_spell_points_for_player, pay_resource,
                        pay_counter, begin_turn_resources,
                        begin_turn_resources_for_player)
from .ability_adapter import MetadataResolutionAdapter
from .resolution import (PortAbilityResolver, NativeEffectBackend,
                         build_port_ability, resolve_port_ability,
                         resolve_port_played_spell, resolve_port_trigger)
from .card_transactions import (CardPlayTransition, CardTransactionExecutor,
                                 MetadataCardTransactionExecutor,
                                 apply_card_play, apply_card_play_for_player)
from .triggers import (MetadataTriggerAdapter, PortTriggerDispatcher,
                        TriggerEvent)
from .metadata import (ability_has_effect, ability_effect_prompt,
                       ability_cost_prompt)
from .trigger_discovery import RecordsTriggerDiscovery, TriggerCandidate
from .conditions import (ConditionContext, PortConditionContext,
                         evaluate_condition, evaluate_effect_condition,
                         trigger_condition_met)
from .targets import MetadataTargetAdapter, TargetSelection
from .targets import FilteredTargetAdapter, target_from_metadata
from .async_bridge import (AsyncActivationPublisher, AsyncEventPublisher,
                           AsyncRulesCoordinator, AsyncUIEventBus)
from .wire import (extract_session_card_uids, normalize_player_transaction,
                    submit_classified_transaction)
from .filters import (AndCardFilter, CardFilter, InZone, IsControlledBy,
                      IsTapped, IsType, NotCardFilter, OrCardFilter, InCollection,
                      HasAnyAttributeFlags, HasCastingCost, HasKeywordAbility,
                      HasName, IsRarity,
                      HasTag, IsSubType, IsMultiThresholdCard,
                      IsColor, InFaction,
                      HasResourceCost, HasAttackValue, HasDefenseValue,
                      IsSocketable, IsSocketed,
                      IsToken, IsResource, IsQuick, IsTroop, IsArtifact,
                      IsChampion, IsHero, IsDamaged, IsAttacking, IsBlocking,
                      IsNotType, IsAlternateArt, IsExtendedArt, IsPromo,
                      IsNotControlledBy, IsPlayedThisTurn, IsDamagedThisTurn,
                      IsHealedThisTurn,
                      filter_from_metadata)

__all__ = (
    "AbilityRegistry", "Chain", "GameAction", "GameActionResult", "GameActionStack",
    "MultiplyWithCarryRng", "PriorityWindowAction", "TurnPhasePlayers",
    "permitted_next_phases", "require_legal_transition", "transition_is_legal",
    "AuthoritativeSession", "PvpAuthoritativeSession", "GameEngineEventSink",
    "RulesTransaction",
    "SQLiteRulesSnapshot",
    "pvp_session_from_persisted_game",
    "TransactionProjection",
    "AbilityCanBeActivatedRequirement", "AbilityExistsRequirement",
    "AbilityHasValidTargetsRequirement", "AllDamageAssignedRequirement",
    "AbilityHasTriggerRequirement", "AbilityIsManuallyActivatedRequirement",
    "AbilityCostRequirement",
    "AbilitiesAreTriggeredRequirement", "BlocksAreValidRequirement",
    "AndRequirement", "AttackExistsRequirement", "AttackerIsValidRequirement",
    "CardCanBePlayedRequirement", "CardCanUntapRequirement",
    "CardUntappedRequirement",
    "CardCountRequirement",
    "CardCastingCostRequirement", "CardInCollectionRequirement",
    "CardResourceThresholdRequirement", "CardTappedRequirement",
    "PlayerHasResourceCountRequirement", "SessionCardAttributesRequirement",
    "SpellAllowedInTurnPhaseRequirement",
    "TurnCountRequirement",
    "CardTypeRequirement", "DefenseDeclarationsLegalRequirement",
    "CardInPlayableLocationRequirement", "SpaceInCardCollectionRequirement",
    "PlayerHasChargePointsRequirement", "PlayerIsInactiveRequirement",
    "PlayerIsStartingPlayerRequirement",
    "EmptyChainRequirement", "MainPhaseRequirement",
    "NotRequirement", "OrRequirement", "PlayerHasPriorityRequirement",
    "PlayerIsActiveRequirement", "PlayerIsNotEliminatedRequirement",
    "PlayerIsAtFrontOfTriggeredAbilityQueueRequirement",
    "PlayerIsResponsibleForAbilityRequirement", "PriorityWindowRequirement",
    "TurnPhaseRequirement", "XCostRequirement",
    "AbilityFactory", "AbilityInstance",
    "session_from_persisted_game", "rules_session_for", "enable_rules_port",
    "PvpRuntimeFacts", "RuntimeCard", "RuntimePlayer", "SQLiteCardMutationAdapter",
    "attach_pvp_runtime_facts",
    "Combat", "CombatFlags", "CombatId", "CombatManager", "CombatPhase",
    "CombatResolver", "CombatResult", "CombatDamageBackend",
    "player_has_eligible_attackers",
    "ConditionalPhaseState", "FirstMainPhaseState", "PriorityPhaseState",
    "StartTurnState", "TurnPhaseState",
    "TurnPhaseTrigger",
    "ParityCapture", "ParityMismatch", "compare_captures", "event_record",
    "replay_transactions",
    "AbilityResolutionState", "PushOntoChainAction", "ResolveTopOfChainAction",
    "AbilityCostPlan", "plan_ability_cost",
    "apply_ability_cost_plan",
    "AbilityCostTarget", "ability_cost_targets",
    "cost_type_for_kind",
    "card_cost_targets",
    "ResourceChange", "ResourcePlay", "apply_resource_change", "play_resource",
    "play_resource_for_player",
    "pay_resource_for_player",
    "pay_charge_for_player",
    "pay_spell_points_for_player",
    "pay_resource",
    "pay_counter",
    "begin_turn_resources",
    "begin_turn_resources_for_player",
    "MetadataResolutionAdapter",
    "PortAbilityResolver", "NativeEffectBackend",
    "build_port_ability",
    "resolve_port_ability",
    "CardTransactionExecutor",
    "MetadataCardTransactionExecutor",
    "CardPlayTransition", "apply_card_play", "apply_card_play_for_player",
    "MetadataTriggerAdapter", "PortTriggerDispatcher",
    "TriggerEvent", "RecordsTriggerDiscovery",
    "ability_has_effect", "ability_effect_prompt", "ability_cost_prompt",
    "TriggerCandidate", "ConditionContext", "PortConditionContext",
    "evaluate_condition", "evaluate_effect_condition",
    "trigger_condition_met",
    "MetadataTargetAdapter", "TargetSelection",
    "FilteredTargetAdapter",
    "target_from_metadata",
    "AsyncUIEventBus", "AsyncActivationPublisher", "AsyncEventPublisher",
    "AsyncRulesCoordinator",
    "extract_session_card_uids", "normalize_player_transaction",
    "submit_classified_transaction",
    "CardFilter", "InZone", "IsTapped", "IsType", "IsControlledBy",
    "AndCardFilter", "OrCardFilter", "NotCardFilter",
    "InCollection", "HasAnyAttributeFlags", "HasCastingCost",
    "HasKeywordAbility", "IsToken", "IsResource", "IsQuick",
    "HasName", "IsRarity",
    "HasTag", "IsSubType", "IsMultiThresholdCard",
    "IsColor", "InFaction",
    "HasResourceCost", "HasAttackValue", "HasDefenseValue",
    "IsSocketable", "IsSocketed",
    "filter_from_metadata",
    "requirement_from_metadata",
    "EComparisons",
    "TRANSACTION_COVERAGE", "coverage_summary",
    "FILTER_COVERAGE", "validate_transaction_coverage", "validate_filter_coverage",
    "coverage_report", "validate_effect_coverage", "STRUCTURAL_EFFECTS",
    "STAGED_EFFECTS",
    "IsTroop", "IsArtifact", "IsDamaged", "IsAttacking", "IsBlocking",
    "IsChampion", "IsHero",
    "IsNotType", "IsAlternateArt", "IsExtendedArt", "IsPromo",
    "IsNotControlledBy", "IsPlayedThisTurn", "IsDamagedThisTurn",
    "IsHealedThisTurn",
)
